### ISSUE TITLE
copy readme.txt to readme.md

### ISSUE THREAD

**Issue by Pomax** [Microsoft/Font-Validator#9]
Right now all the instructions are in the readme.txt, with almost nothing in the readme.md, even though github will show the readme.md as the authoritative readme documentation. It's worth either copying the contents of readme.txt to readme.md, or rename the .txt version to .md, so that instructions are immediately visible.

**Comment by HinTak** [comment]
That's Aaron and Microsoft folks' decision...

**Comment by Pomax** [comment]
@aaronbell, as most people are now going to find this repo, and the README.md is the public face for this codebase, worth doing?

**Comment by davelab6** [comment]
I submitted a PR for this i think

**Comment by Pomax** [comment]
I only see [two PRs at the moment](https://github.com/Microsoft/Font-Validator/pulls), maybe the PR never went through?

**Comment by HinTak** [comment]
Dave's issue report was against my fork, and I merged and closed it against mine - so the upstream Microsoft parent would inherit it if/when I sign the CLA. Until then, please feel free to file another against upstream... :-).

**Comment by Pomax** [comment]
ahh, noted. let me close this =)

**Comment by HinTak** [comment]
Perhaps closed too soon - the earlier discussion about whether I should act as a CLA by-pass applies (though in this case thisconsideration may be over-cautious), also, when I merged,  i did wonder whether this should be dealt with by the Microsoft folks, since their lawyers(!) care more about what to the front, so they might still turn it down in the end. For now, it only goes to my front, and I am okay with that.

**Comment by Pomax** [comment]
same here, that sounds fine.
